In [10]:
import numpy as np

In [11]:
l=[56,45,34,89,50]
l_array=np.array(l)

In [12]:
l_array

array([56, 45, 34, 89, 50])

In [13]:
l=len(l_array)
divide_array=np.array_split(l_array,l)
    

In [14]:
divide_array

[array([56]), array([45]), array([34]), array([89]), array([50])]

In [15]:
divide_array[0]

array([56])

In [16]:
divide_array[1]

array([45])

In [17]:
def msort(divide_array,l,i):
    if (i+1)!=l: 
        if divide_array[i]<divide_array[i+1]:
            sorted_list=np.append(divide_array[i],divide_array[i+1])
            l_array[i]=divide_array[i]
            l_array[i+1]=divide_array[i+1]
        if divide_array[i]>divide_array[i+1]:
            sorted_list=np.append(divide_array[i+1],divide_array[i])
            l_array[i],l_array[i+1]=l_array[i+1],l_array[i]
    else:
        l_array[i]=divide_array[i]
        sorted_list=divide_array[i]
    print(sorted_list)
       

In [18]:
l=len(l_array)
for i in range (0,l,2):
    msort(divide_array,l,i)
        

[45 56]
[34 89]
[50]


In [19]:
l_array

array([45, 56, 34, 89, 50])

In [20]:
#not able to understand how to combine and compare and prepare an array of 4 and 1..........
#Now I have taken help from the net and understood step by step by using printf command.

In [21]:
def divide(arr): 
    if len(arr) >1: 
        mid = len(arr)//2  
        L = arr[:mid] 
        R = arr[mid:]
        print("L=")
        print(L)
        divide(L)
        print("R=")
        print(R)
        divide(R)
        print("sort")
        i = j = k = 0
        print("i=",i,"j=",j,"k=",k)
        while i < len(L) and j < len(R): 
            if L[i] < R[j]: 
                arr[k] = L[i] 
                i+=1
            else: 
                arr[k] = R[j] 
                j+=1
            k+=1
            print(arr)
            print("i=",i,"j=",j,"k=",k)
            
        print("final sort")
        while i < len(L):
            print("i=")
            print(i)
            arr[k] = L[i]
            i+=1
            k+=1
            print(arr)
            print(".............")
        while j < len(R):
            print("J=")
            print(j)
            arr[k] = R[j] 
            j+=1
            k+=1
            print(arr)
            print(".............")
        
       
        
        

In [22]:
arr=[34,3,8,77,1,44,4]
print(arr)
print("after dividing")
divide(arr)


[34, 3, 8, 77, 1, 44, 4]
after dividing
L=
[34, 3, 8]
L=
[34]
R=
[3, 8]
L=
[3]
R=
[8]
sort
i= 0 j= 0 k= 0
[3, 8]
i= 1 j= 0 k= 1
final sort
J=
0
[3, 8]
.............
sort
i= 0 j= 0 k= 0
[3, 3, 8]
i= 0 j= 1 k= 1
[3, 8, 8]
i= 0 j= 2 k= 2
final sort
i=
0
[3, 8, 34]
.............
R=
[77, 1, 44, 4]
L=
[77, 1]
L=
[77]
R=
[1]
sort
i= 0 j= 0 k= 0
[1, 1]
i= 0 j= 1 k= 1
final sort
i=
0
[1, 77]
.............
R=
[44, 4]
L=
[44]
R=
[4]
sort
i= 0 j= 0 k= 0
[4, 4]
i= 0 j= 1 k= 1
final sort
i=
0
[4, 44]
.............
sort
i= 0 j= 0 k= 0
[1, 1, 44, 4]
i= 1 j= 0 k= 1
[1, 4, 44, 4]
i= 1 j= 1 k= 2
[1, 4, 44, 4]
i= 1 j= 2 k= 3
final sort
i=
1
[1, 4, 44, 77]
.............
sort
i= 0 j= 0 k= 0
[1, 3, 8, 77, 1, 44, 4]
i= 0 j= 1 k= 1
[1, 3, 8, 77, 1, 44, 4]
i= 1 j= 1 k= 2
[1, 3, 4, 77, 1, 44, 4]
i= 1 j= 2 k= 3
[1, 3, 4, 8, 1, 44, 4]
i= 2 j= 2 k= 4
[1, 3, 4, 8, 34, 44, 4]
i= 3 j= 2 k= 5
final sort
J=
2
[1, 3, 4, 8, 34, 44, 4]
.............
J=
3
[1, 3, 4, 8, 34, 44, 77]
.............


In [23]:
arr

[1, 3, 4, 8, 34, 44, 77]

In [29]:
def mergeSort(arr): 
    if len(arr) >1: 
        mid = len(arr)//2  
        L = arr[:mid] 
        R = arr[mid:] 
  
        mergeSort(L) 
        mergeSort(R)  
  
        i = j = k = 0
        while i < len(L) and j < len(R): 
            if L[i] < R[j]: 
                arr[k] = L[i] 
                i+=1
            else: 
                arr[k] = R[j] 
                j+=1
            k+=1
        while i < len(L): 
            arr[k] = L[i] 
            i+=1
            k+=1
          
        while j < len(R): 
            arr[k] = R[j] 
            j+=1
            k+=1

In [41]:
random_array=np.random.randint(0,1000,5)
random_array=list(random_array)
print(random_array)
mergeSort(random_array)
print(random_array)

[382, 487, 254, 586, 691]
[254, 382, 487, 586, 691]


In [44]:
new_random_array=np.random.randint(0,1000,1000)
new_random_array=list(new_random_array)
print(new_random_array)
mergeSort(new_random_array)
print(new_random_array)

[529, 81, 187, 58, 837, 67, 579, 122, 310, 187, 979, 782, 990, 780, 514, 613, 775, 744, 377, 334, 547, 74, 427, 568, 858, 111, 663, 318, 402, 367, 219, 736, 277, 532, 855, 401, 115, 35, 228, 228, 477, 768, 7, 971, 941, 820, 761, 456, 982, 725, 319, 18, 169, 504, 163, 885, 646, 357, 378, 236, 2, 347, 36, 950, 149, 821, 37, 808, 345, 579, 911, 147, 625, 755, 703, 162, 62, 941, 269, 201, 592, 402, 970, 589, 333, 53, 119, 986, 894, 61, 954, 660, 160, 699, 606, 288, 723, 24, 92, 877, 302, 387, 800, 495, 913, 61, 772, 684, 340, 35, 10, 93, 626, 262, 893, 906, 341, 297, 954, 854, 482, 70, 519, 99, 839, 330, 572, 988, 51, 247, 127, 694, 277, 871, 412, 893, 289, 651, 255, 454, 401, 154, 774, 553, 176, 74, 333, 567, 685, 520, 87, 592, 537, 78, 928, 333, 273, 918, 396, 865, 46, 122, 175, 256, 900, 784, 414, 801, 666, 411, 42, 519, 228, 244, 540, 848, 260, 905, 79, 607, 939, 954, 317, 798, 785, 142, 904, 991, 881, 727, 898, 883, 721, 992, 53, 299, 626, 853, 591, 947, 36, 259, 69, 746, 755, 941, 47